### login
POST http://localhost:3000/user/login
Content-Type: application/json

{
	"username": "zhangsan",
	"password": "111111"
}

### aaa
GET http://localhost:3000/bbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN1YiI6MSwidXNlcm5hbWUiOiJ6aGFuZ3NhbiIsInJvbGVzIjpbeyJpZCI6MSwibmFtZSI6ImFhYSIsImNyZWF0ZWRBdCI6IjIwMjUtMDItMTFUMDM6MzM6MzMuMDA4WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDItMTFUMDM6MzM6MzMuMDA4WiJ9LHsiaWQiOjIsIm5hbWUiOiJiYmIiLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTExVDAzOjMzOjMzLjAxNVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTExVDAzOjMzOjMzLjAxNVoifV19LCJpYXQiOjE3Mzk2ODk3MzEsImV4cCI6MTczOTY5MzMzMX0.GioMyPkb96f1Ib1P8YDRkOo9KPzGAmIMQg7J5hBqtM8
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN1YiI6MywidXNlcm5hbWUiOiJ3YW5nd3UiLCJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJiYmIiLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTExVDAzOjMzOjMzLjAxNVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTExVDAzOjMzOjMzLjAxNVoifV19LCJpYXQiOjE3Mzk2MjI5NDQsImV4cCI6MTczOTYyNjU0NH0.HJWGBzD3munzPIPcIV77tth86VeJE2AGqCB-4J4ZeJE

###
GET http://localhost:3000/user/init